# Generated by Django 4.2.27 on 2025-12-22 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("relecloud", "0006_usertravelrecord_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertravelrecord",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
