# Generated by Django 4.2.27 on 2025-12-22 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("relecloud", "0007_alter_usertravelrecord_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opinion",
            name="cruise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opinions",
                to="relecloud.cruise",
            ),
        ),
        migrations.AlterField(
            model_name="usertravelrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
